### PR TITLE
v0.0.2 - Murf initial edits

### PR DESCRIPTION
**Pull request by GitMurf**

### CODE REVIEW

**Comment by GitMurf** [comment]
Did I do this right? My first "official" real pull request for actually changing code ;) Wasn't as bad as I thought, haha.

**Comment by GitMurf** [comment]
Also I could care less about putting my name on the plugin so you can ignore in the manifest.json where I had added my name. I only did that to not confuse folks with the original version you had released.

image

**Comment by shabegom** [comment]
PR looks good! I'm going to pull it down and change a couple of things and then will merge it in! I'll add and .eslintrc so that we're not fighting between 2 spaces and 4. ;)

**Comment by shabegom** [comment]
ah I can't edit cause it's a fork. will merge er in and then make changes

**Comment by GitMurf** [comment]
> ah I can't edit cause it's a fork. will merge er in and then make changes

Sounds good! This is fun :)

**Pull request merged**
